name: context

on:
  workflow_dispatch:
  issues: 
    types: [opened, edited]
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          console.log(context)
