name: Dynamic Services

on:
  workflow_dispatch:
  push:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Node dependencies
        run: npm install js-yaml
      - uses: actions/github-script@v7
        id: config
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const yaml = require('js-yaml');
            const config = yaml.load(fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, '.github', 'actions', 'config', 'service1.yml'), 'utf8'));
            return config.services
  debug:
    runs-on: ubuntu-latest
    needs: config
    steps:
      - name: Debug
        run: echo '${{ fromJson(needs.config.outputs.config) }}'
  runner-job-nginx:
    if: ${{ contains(needs.config.outputs.config.services, 'nginx') }}
    runs-on: ubuntu-latest
    needs: config
    services:
      nginx:
        image: nginx:latest
        ports:
          - ${{ needs.config.outputs.config.port }}:80
    steps:
      - name: Test
        run: curl http://localhost:${{ needs.config.outputs.config.port }}
  runner-job-httpd:
    if: ${{ contains(needs.config.outputs.config.services, 'httpd') }}
    runs-on: ubuntu-latest
    needs: config
    services:
      nginx:
        image: nginx:latest
        ports:
          - ${{ needs.config.outputs.config.port }}:80
    steps:
      - name: Test
        run: curl http://localhost:${{ needs.config.outputs.config.port }}
