name: Dynamic Matrix

on:
  workflow_dispatch:

jobs:
  outputs:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.random-number.outputs.result }}
    steps:
      - id: random-number
        uses: actions/github-script@v6
        with:
          script: |
            const min = 1;
            const max = 5;
            const randomnumber = Math.floor(Math.random() * (max - min + 1)) + min;
            let returnArray = [];
            for (let i = 1; i <= randomnumber; i++) {
              returnArray.push(`matrix${i}`);
            }
            core.info(`Random number: ${randomnumber}`);
            core.info(`Return array: ${returnArray}`);
            return returnArray;

  matrix:
    needs: outputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iteration: ${{ fromJson(needs.outputs.outputs.random-number) }}
    steps:
      - name: Matrix - ${{ matrix.iteration }}
        run: echo ${{ matrix.iteration }}
