name: failure

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 ; exit 1
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
