name: flow-test

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the infrastructure'
        required: true
        default: false
        type: boolean
      import_test:
        description: 'Test the import'
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]
      fail_plan:
        description: 'Fail the plan'
        required: true
        default: false
        type: boolean

jobs:
  plan:
    if: inputs.destroy == false
    runs-on: ubuntu-latest
    outputs:
      requireImport: ${{ steps.requireImport.outputs.requireImport }}
    steps:
    - name: Require Import
      id: requireImport
      run: echo "requireImport=${{ inputs.import_test }}" >> $GITHUB_OUTPUT
    - name: Fail Plan
      if: inputs.fail_plan == true
      run: |
        echo "Plan failed" >> $GITHUB_STEP_SUMMARY
        exit 1
    - run: echo "Plan complete" >> $GITHUB_STEP_SUMMARY

  import:
    needs: plan
    if: needs.plan.outputs.requireImport == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "Importing the infrastructure"
    - run: echo "Import complete" >> $GITHUB_STEP_SUMMARY

  apply:
    needs:
      - plan
      - import
    if: (needs.plan.outputs.requireImport == true && needs.import.result == 'success') || (always() && needs.plan.result == 'success')
    runs-on: ubuntu-latest
    steps:
    - run: echo "Applying the infrastructure"
    - run: echo "Apply complete" >> $GITHUB_STEP_SUMMARY

  destroy:
    if: inputs.destroy == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "Destroying the infrastructure"
    - run: echo "Destroy complete" >> $GITHUB_STEP_SUMMARY
