name: issue-workflow-called

on:
  workflow_call:

permissions:
  issues: read

jobs:
  issue-workflow-called:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(${{ toJson(github.event) }})
            console.log(${{ toJson(github.context) }})
