name: my-workflow

on:
  workflow_dispatch:
    inputs:
      color:
        type: choice
        description: color
        options: 
        - red
        - green
        default: green
      message:
        required: true

permissions: {}

jobs:
  echo-selections:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Message: ${{ github.event.inputs.message }} with color ${{ github.event.inputs.color }}"
        echo $RUNNER_DIR
