name: Retry Workflow

on:
  check_run:
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest
    if: github.event.check_run.conclusion == 'failure'
    steps:
      - name: log context
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
