name: self-hosted-container
on:
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: arc-runner-set-collinmcneese-test
    # container:
    #   image: node:20
    #   env:
    #     NODE_ENV: development
    #   ports:
    #     - 80
    services:
      node:
        image: node:20
        env:
          NODE_ENV: development
        ports:
        - 80
    #   opensearch:
    #     image: opensearchproject/opensearch:latest
    #     env:
    #       discovery.type: single-node
    #       cluster.name: opensearch-cluster
    #       bootstrap.memory_lock: "true"
    #       "OPENSEARCH_JAVA_OPTS": "-Xms512m -Xmx512m"
    #     ports:
    #       - 9200:9200
    #       - 9300:9300
    #     volumes:
    #       - opensearch-data:/usr/share/opensearch/data
    #       - opensearch-logs:/usr/share/opensearch/logs
    #       - opensearch-config:/usr/share/opensearch/config
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
