name: whoami
on:
  workflow_dispatch:

permissions: {}

jobs:
  whoami:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - run: whoami
