name: workflow with protection check

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - production
          - staging
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: check if the selected environment is protected
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let { data } = await github.request('GET /repos/{owner}/{repo}/environments/{environment_name}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: '${{ github.event.inputs.environment }}'
            });

            core.debug(JSON.stringify(data, null, 2));
            // return true if data.protection_rules is not empty
            return data.protection_rules.length > 0;

  deploy:
    needs: check
    if: needs.check.outputs.result == 'true'
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying"
