name: workflow with protection check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the branch is protected
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.ref.replace('refs/heads/', '')
            });
            return branch.protected;
      - name: branch is not protected
        if: steps.check.outputs.result == 'false'
        run: exit 1
      - name: branch is protected
        if: steps.check.outputs.result == 'true'
        run: echo "Branch is protected"
